name: multi_window
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  multi_window_interface: # ^0.1.0
    path: ../multi_window_interface
  multi_window_linux: # ^0.1.0
    path: ../multi_window_linux

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        default_package: multi_window_linux
